### ISSUE TITLE
document macOS install for dependencies

### ISSUE THREAD

**Issue by micahstubbs** [iamjakewarner/jdf#4]
thanks for the project!

it would be nice to document the macOS install process for dependencies, like `pdflatex`

**Comment by micahstubbs** [comment]
here is one possible answer https://superuser.com/questions/1038612/where-do-i-get-the-pdflatex-program-for-mac

**Comment by micahstubbs** [comment]
```bash
brew cask install mactex
mactex
which pdflatex
```

**Comment by iamjakewarner** [comment]
There are many ways to install LaTeX on different operating systems, and documenting all of them is beyond the scope of this repo. As I said in the README, I personally use a distribution called [MacTeX](https://www.tug.org/mactex/index.html). In my opinion, it’s the best way to ensure that you have all the required dependencies. Since you’re on Mac, you should consider it. You can also read about the differences between MacTeX and BasicTeX on the MacTeX site.
